services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "81:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: my_laravel_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
